### ISSUE TITLE
ckite-mapdb de/serializeSnapshot() not implemented

### ISSUE THREAD

**Issue by jmarchesini** [pablosmedina/ckite#13]
Hi Pablo -

We've been using ckite with great success so far.  Today, I tried using MapDB for persistence and ran into a problem: looks like two methods that are called during startup are not yet implemented (or perhaps I'm looking in the wrong place).

My builder:

val ckite = CKiteBuilder()
      .stateMachine(new KVStore())
      .rpc(FinagleThriftRpc)
      .bootstrap(bootstrap)
      .members(nodes.asScala)
      .storage(new MapDBStorage(dataDir))
      .build

And "io.ckite" % "ckite-mapdb" % "0.2.0", "org.mapdb" % "mapdb" % "0.9.13" are in my build.sbt libraryDependencies.

I see the dataDir get populated with 'log', 'snapshots', and 'state' as expected, but RLog looks like it is trying to reload a snapshot on startup, which eventually calls ckite.mapdb.MapDBStorage.deserializeSnapshot.

I'm looking at the src here: https://github.com/pablosmedina/ckite/blob/master/ckite-mapdb/src/main/scala/ckite/mapdb/MapDBStorage.scala, and it looks like the method isn't implemented.

Is this a bug or am I missing something?

Here's the trace:

[key-value-store-system-akka.actor.default-dispatcher-3] INFO   - 16:39:55,327 - witter.finagle.Init$$anonfun$1#apply$mcV$sp: Finagle version 6.27.0 (rev=65df1512aadc8b79871a6dcafbbd210fd088b055) built at 20150727-172532
2015-09-18 16:39:55 INFO  Raft:18 - Starting CKite localhost:9091...
2015-09-18 16:39:55 INFO  RLog:156 - Initializing RLog...
[ERROR] [09/18/2015 16:39:55.913] [key-value-store-system-akka.actor.default-dispatcher-3] [LocalActorRefProvider(akka://key-value-store-system)] guardian failed, shutting down system
scala.NotImplementedError: an implementation is missing
	at scala.Predef$.$qmark$qmark$qmark(Predef.scala:225)
	at ckite.mapdb.MapDBStorage.deserializeSnapshot(MapDBStorage.scala:41)
	at ckite.mapdb.MapDBStorage.retrieveLatestSnapshot(MapDBStorage.scala:25)
	at ckite.rlog.SnapshotManager.latestSnapshot(SnapshotManager.scala:76)
	at ckite.RLog.reloadSnapshot(RLog.scala:172)
	at ckite.RLog.replay(RLog.scala:164)
	at ckite.RLog.initialize(RLog.scala:158)
	at ckite.Raft.initializeLog(Raft.scala:29)
	at ckite.Raft.start(Raft.scala:19)
	at ckite.CKiteClient.start(CKiteClient.scala:35)
	at . . . 

Thanks for the help and I'm happy to test a fix.

John

**Comment by pablosmedina** [comment]
Hi John,

I'm glad everything is ok with ckite so far. Sadly, it seems I lost a commit on the latest release with all the changes and refactors on it. Nevermind, I've just pushed a snapshot version to Sonatype with a fix. The version is 0.2.1-SNAPSHOT. You can find it on Sonatype repo, not yet in Maven central. 
Please play a bit with that version and if everything is ok I'll push it to Maven central.

Thanks!

**Comment by jmarchesini** [comment]
Hi Pablo -

Thanks for the quick turnaround!  I've pulled down 0.2.1-SNAPSHOT for core, mapdb, and finagle and I've started testing.

I'll keep you posted.

Thanks again,
John

**Comment by jmarchesini** [comment]
Hi Pablo -

So far, things are looking great.  One quick clarification:

When I'm using MapDB for persistence, it seems like I only bootstrap once - when the log is empty.  If I attempt to bootstrap after that, I get "Log is not empty."  (Stack trace below.)

This is actually very nice for us operationally, I just want to be sure I'm using the feature as intended.

Thanks!

John

java.lang.IllegalStateException: Log is not empty
	at ckite.RLog.assertEmptyLog(RLog.scala:148)
	at ckite.RLog.bootstrap(RLog.scala:48)
	at ckite.Raft.bootstrapStart(Raft.scala:45)
	at ckite.Raft.start(Raft.scala:21)
	at ckite.CKiteClient.start(CKiteClient.scala:35)

**Comment by pablosmedina** [comment]
Hi John,

You only have to bootstrap CKite the very first time. That check prevents you from accidentally diverging the log by having a second leader. If you have to bootstrap the cluster again then you have to delete the log and start again (please note that for now this assumes you have a persistent state machine). Hope that is clear to you.
I'll push the fix release to Maven central in a few hours.

Cheers!

**Comment by jmarchesini** [comment]
Hi Pablo -

Did you ever send 0.2.1 to Maven central?  I'm only seeing 0.2.0:

http://search.maven.org/#search%7Cga%7C1%7Cckite

I'm still pulling 0.2.1 from sonatypeRepo("snapshots") - so no huge rush.  I'll close this when they're on central.

Thanks again,
John

**Comment by pablosmedina** [comment]
Hi John,

I'll push a new version tomorrow including a fix to the other issue you have opened regarding the listen address configuration.

Thanks,
Pablo

**Comment by pablosmedina** [comment]
Hi John,

I've just pushed the release version 0.2.1 to Sonatype and it will be available at Maven Central in a few hours. Please take a look at it and let me know if you have any issues.

Pablo

**Comment by jmarchesini** [comment]
Got it - everything is resolved and 0.2.1 is in central.

Thanks!
