### ISSUE TITLE
ckite Builder always uses ckite.finagle.listen-address in .conf file

### ISSUE THREAD

**Issue by jmarchesini** [pablosmedina/ckite#14]
Hi Pablo -

It seems that the builder always does a file lookup (perhaps ConfigFactor.load.getConfig("ckite")) when fetching the listen-address.

I've tried to supply a different value in the Builder as you do in the examples with no luck.  I've also tried something like this before constructing the builder:

 val config = originalConfig.withValue("ckite.finagle.listen-address", ConfigValueFactory.fromAnyRef(myListenAddress))

If I remove the value from my config file, I get an exception.

Ultimately, I need to be set this on each of my nodes at runtime since I can only make a single deployment package for all of my nodes.

Thanks for the help,
John

**Comment by pablosmedina** [comment]
John,

I've fixed the listenAddress configuration trough the builder in the latest version 0.2.1. You can configure the listenAddress using the builder or by the configuration key ckite.listen-address. Please not that I've changed the key from 'ckite.finagle.listen-address' to 'ckite.listen-address'. Hope that helps. Let me know if that works to you.

Pablo

**Comment by jmarchesini** [comment]
Hi Pablo -

This works great - thanks for the quick turnaround as usual!

John
